### ISSUE TITLE
API Controllers giving wrong responses

### ISSUE THREAD

**Issue by TobiasJ** [raghibhuda/alexandria#6]
https://github.com/raghibhuda/alexandria/blob/master/app/Http/Controllers/API/AuthorController.php#L31

```php
// @create
$createAuthorResponse = $this->authorService->create($name,$bio); // returns ['success' => false, 'message' => __('Failed to create Author')]
return response()->json(['success' => true, 'message' => $createAuthorResponse['message']]);
// should be
return response()->json($createAuthorResponse);
// ...
```

You should simply throw an error in the service that gives a good indication on what went wrong, then catch it in your controller and pass the message to the response and set correct http-status codes...

**Comment by raghibhuda** [comment]
Thanks for pointing out. I have fixed this too
